import { MedusaService } from "@medusajs/framework/utils";
import {
  AuditEvent,
  BrandingProfile,
  ProductPolicy,
  Supplier,
  SupplierOffer,
  SupplierVariantMap,
  ImportDraft,
  ImportAttempt,
  CostQuote,
  PricingSnapshot,
  ShippingQuote,
  SupplierRoutingDecision,
  CheckoutSession,
  CheckoutShippingSelection,
  TaxpayerIdentity,
  PaymentIntent,
  PaymentProviderEvent,
  CustomerOrder,
  SupplierFulfillmentPlan,
  FulfillmentGroup,
  SupplierOrder,
  FulfillmentTracking,
  OrderException,
} from "./models";

class SupplierDomainModuleService extends MedusaService({
  Supplier,
  SupplierOffer,
  SupplierVariantMap,
  BrandingProfile,
  ProductPolicy,
  AuditEvent,
  ImportDraft,
  ImportAttempt,
  CostQuote,
  PricingSnapshot,
  ShippingQuote,
  SupplierRoutingDecision,
  CheckoutSession,
  CheckoutShippingSelection,
  TaxpayerIdentity,
  PaymentIntent,
  PaymentProviderEvent,
  CustomerOrder,
  SupplierFulfillmentPlan,
  FulfillmentGroup,
  SupplierOrder,
  FulfillmentTracking,
  OrderException,
}) {}

export default SupplierDomainModuleService;
